package com.java.mmzsit.mapper;

import com.java.mmzsit.model.testdatas;

public interface testdatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTDATAS
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTDATAS
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    int insert(testdatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTDATAS
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    int insertSelective(testdatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTDATAS
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    testdatas selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTDATAS
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    int updateByPrimaryKeySelective(testdatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTDATAS
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    int updateByPrimaryKey(testdatas record);
}