package com.java.mmzsit.model;

public class testdatas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTDATAS.ID
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTDATAS.NAME
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTDATAS.AGE
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    private Object age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTDATAS.INFORMATION
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    private Object information;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTDATAS.UPDATEDATE
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    private Object updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTDATAS.ID
     *
     * @return the value of TESTDATAS.ID
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTDATAS.ID
     *
     * @param id the value for TESTDATAS.ID
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTDATAS.NAME
     *
     * @return the value of TESTDATAS.NAME
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTDATAS.NAME
     *
     * @param name the value for TESTDATAS.NAME
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTDATAS.AGE
     *
     * @return the value of TESTDATAS.AGE
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public Object getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTDATAS.AGE
     *
     * @param age the value for TESTDATAS.AGE
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public void setAge(Object age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTDATAS.INFORMATION
     *
     * @return the value of TESTDATAS.INFORMATION
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public Object getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTDATAS.INFORMATION
     *
     * @param information the value for TESTDATAS.INFORMATION
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public void setInformation(Object information) {
        this.information = information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTDATAS.UPDATEDATE
     *
     * @return the value of TESTDATAS.UPDATEDATE
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public Object getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTDATAS.UPDATEDATE
     *
     * @param updatedate the value for TESTDATAS.UPDATEDATE
     *
     * @mbggenerated Wed Jun 12 17:08:17 CST 2019
     */
    public void setUpdatedate(Object updatedate) {
        this.updatedate = updatedate;
    }
}